/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./components/base/badge/Badge.vue')['default']
    Button: typeof import('./components/base/button/Button.vue')['default']
    Card: typeof import('./components/base/card/Card.vue')['default']
    CardContent: typeof import('./components/base/card/CardContent.vue')['default']
    CardDescription: typeof import('./components/base/card/CardDescription.vue')['default']
    CardFooter: typeof import('./components/base/card/CardFooter.vue')['default']
    CardHeader: typeof import('./components/base/card/CardHeader.vue')['default']
    CardTitle: typeof import('./components/base/card/CardTitle.vue')['default']
    Checkbox: typeof import('./components/base/checkbox/Checkbox.vue')['default']
    DropdownMenu: typeof import('./components/base/dropdown-menu/DropdownMenu.vue')['default']
    DropdownMenuCheckboxItem: typeof import('./components/base/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    DropdownMenuContent: typeof import('./components/base/dropdown-menu/DropdownMenuContent.vue')['default']
    DropdownMenuGroup: typeof import('./components/base/dropdown-menu/DropdownMenuGroup.vue')['default']
    DropdownMenuItem: typeof import('./components/base/dropdown-menu/DropdownMenuItem.vue')['default']
    DropdownMenuLabel: typeof import('./components/base/dropdown-menu/DropdownMenuLabel.vue')['default']
    DropdownMenuRadioGroup: typeof import('./components/base/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    DropdownMenuRadioItem: typeof import('./components/base/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    DropdownMenuSeparator: typeof import('./components/base/dropdown-menu/DropdownMenuSeparator.vue')['default']
    DropdownMenuShortcut: typeof import('./components/base/dropdown-menu/DropdownMenuShortcut.vue')['default']
    DropdownMenuSub: typeof import('./components/base/dropdown-menu/DropdownMenuSub.vue')['default']
    DropdownMenuSubContent: typeof import('./components/base/dropdown-menu/DropdownMenuSubContent.vue')['default']
    DropdownMenuSubTrigger: typeof import('./components/base/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    DropdownMenuTrigger: typeof import('./components/base/dropdown-menu/DropdownMenuTrigger.vue')['default']
    Input: typeof import('./components/base/input/Input.vue')['default']
    Label: typeof import('./components/base/label/Label.vue')['default']
    Sheet: typeof import('./components/base/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./components/base/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./components/base/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./components/base/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./components/base/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./components/base/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./components/base/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./components/base/sheet/SheetTrigger.vue')['default']
    Switch: typeof import('./components/base/switch/Switch.vue')['default']
    Toast: typeof import('./components/base/toast/Toast.vue')['default']
    ToastAction: typeof import('./components/base/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./components/base/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./components/base/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./components/base/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./components/base/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./components/base/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./components/base/toast/ToastViewport.vue')['default']
  }
}
